name: PushToDB

on:
  push:
    branches: [ "TechnoMagic" ]
  pull_request:
    branches: [ "TechnoMagic" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  apiKey: "AIzaSyCmdvetArnso__3r8F9Qst8XPghuT4_Uh8"
  authDomain: "o6i7ry.firebaseapp.com"
  databaseURL: "https://o6i7ry-default-rtdb.firebaseio.com"
  projectId: "o6i7ry"
  storageBucket: "o6i7ry.appspot.com"
  messagingSenderId: "713136587345"
  appId: "1:713136587345:web:1d18406f69f1c3c356ae70"
  
  
jobs:
  pushToDB:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: push
      run: |
        npm install
        npm run push_to_db
